### PR TITLE
Fix/multiple bugs

### LINKED ISSUE #12: `EXTRA_FLAGS` option is ineffective
`EXTRA_FLAGS` is not read here, thus the option is ineffective at the moment:

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/options/options.go#L35-L61

This also looks like dead code:

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/options/options.go#L25-L33

### LINKED ISSUE #13: Spliting of extra flags is too naive
Splitting by spaces will not work in many cases

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/ssh/ssh.go#L50

Here's an example with a `ProxyCommand` that would break:

```
EXTRA_FLAGS='-i~/.ssh/google_compute_engine -oProxyCommand="gcloud compute start-iap-tunnel %h %p --listen-on-stdin --project=<project> --zone=<region> --verbosity=warning"'
```

There are libraries out there that do "shell-like" splitting, I have not done the research to figure which one is best.

Extra note: the reproduction command in the error message is missing a space after `ssh`, it should be `"ssh "`:

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/ssh/ssh.go#L39

### PR DESCRIPTION
**Pull request by 89luca89**
Fix #12
Fix #13 
Resolves ENG-1941
Resolves ENG-1943

Resolve reported bugs for extra flags picking and splitting

### CODE REVIEW

File: pkg/ssh/ssh.go [hunk 1]
```diff
@@ -47,7 +48,10 @@ func getSSHCommand(provider *SSHProvider) []string {
 	}
 
 	if provider.Config.ExtraFlags != "" {
-		result = append(result, strings.Split(provider.Config.ExtraFlags, " ")...)
+		flags, err := shellquote.Split(provider.Config.ExtraFlags)
```
Comment (pbialon) [inline pkg/ssh/ssh.go:51]: do we want to ignore the error completely?

Comment (89luca89) [reply pkg/ssh/ssh.go:57]: Right! Fixed it :+1:

**Review by pbialon — APPROVED** [review]
